import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, SMARTWATCH_CONSTANTS } from '../../services/constants';

const { width, height } = Dimensions.get('window');

export const createStyles = () => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.PRIMARY,
    paddingTop: 0,
    paddingHorizontal: 15,
    paddingBottom: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    marginTop: -40,
    marginBottom: 20,
    alignItems: 'center',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 10,
    width: '100%',
  },
  infoButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.BACKGROUND,
    marginRight: 25,
    marginTop: 10,
  },
  infoButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: COLORS.BACKGROUND,
  },
  title: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_LARGE,
    fontWeight: 'bold',
    color: COLORS.BACKGROUND,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_MEDIUM,
    color: COLORS.BACKGROUND,
    opacity: 0.8,
  },
  userInfo: {
    alignItems: 'center',
    flex: 1,
    marginLeft: 60,
    marginRight: 0,
    marginTop: 20,
    marginBottom: 0,
  },
  userText: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL,
    color: COLORS.BACKGROUND,
    marginBottom: 3,
    fontWeight: 'bold',
  },
  statusText: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL - 1,
    color: COLORS.BACKGROUND,
    opacity: 0.8,
    marginBottom: 1,
  },
  sosButton: {
    width: Math.min(width * 0.8, 180),
    height: Math.min(width * 0.8, 180),
    borderRadius: Math.min(width * 0.4, 90),
    backgroundColor: '#FF0000',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 0,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sosButtonActive: {
    backgroundColor: '#FF3333',
    transform: [{ scale: 1.1 }],
  },
  sosContent: {
    alignItems: 'center',
    paddingTop: 0,
  },
  sosText: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_MEDIUM + 2,
    fontWeight: '900',
    color: COLORS.BACKGROUND,
    textAlign: 'center',
    letterSpacing: 2,
  },
  sosSubtext: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_MEDIUM,
    fontWeight: 'bold',
    color: COLORS.BACKGROUND,
    opacity: 0.9,
  },
  sosCountdown: {
    alignItems: 'center',
  },
  sosCountdownText: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_MEDIUM,
    fontWeight: 'bold',
    color: COLORS.BACKGROUND,
    marginBottom: 2,
  },
  sosCountdownLabel: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL,
    color: COLORS.BACKGROUND,
    opacity: 0.9,
  },
  sosLoading: {
    alignItems: 'center',
  },
  sosLoadingText: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL,
    color: COLORS.BACKGROUND,
    opacity: 0.9,
    marginTop: 10,
  },
  infoSection: {
    alignItems: 'center',
    marginVertical: 20,
  },
  infoText: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_MEDIUM,
    color: COLORS.BACKGROUND,
    textAlign: 'center',
    marginBottom: 5,
  },
  infoSubtext: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL,
    color: COLORS.BACKGROUND,
    opacity: 0.8,
    textAlign: 'center',
  },
  shakeToggleButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: 2,
    borderRadius: 3,
    alignItems: 'center',
    marginBottom: 0,
    marginTop: 5,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    width: '40%',
    alignSelf: 'center',
  },
  shakeToggleButtonActive: {
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderColor: 'rgba(76, 175, 80, 0.5)',
  },
  toggleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  toggleContent: {
    flex: 1,
    alignItems: 'flex-start',
  },
  shakeToggleText: {
    color: COLORS.BACKGROUND,
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL - 1,
    fontWeight: 'bold',
    marginBottom: 0,
  },
  shakeToggleSubtext: {
    color: COLORS.BACKGROUND,
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL - 3,
    opacity: 0.8,
    textAlign: 'left',
  },
  toggleSwitch: {
    width: 24,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    paddingHorizontal: 1,
    marginRight: 6,
  },
  toggleSwitchActive: {
    backgroundColor: 'rgba(76, 175, 80, 0.8)',
  },
  toggleThumb: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.BACKGROUND,
    alignSelf: 'flex-start',
  },
  toggleThumbActive: {
    alignSelf: 'flex-end',
  },
  logoutButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: 5,
    borderRadius: 3,
    alignItems: 'center',
    marginBottom: 0,
    marginTop: 5,
    width: '35%', // Make button smaller in width
    alignSelf: 'center', // Center the button
  },
  logoutText: {
    color: COLORS.BACKGROUND,
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL,
    fontWeight: 'bold',
  },
  errorContainer: {
    backgroundColor: 'rgba(255, 0, 0, 0.1)',
    padding: 15,
    borderRadius: 5,
    marginVertical: 20,
  },
  errorText: {
    color: COLORS.BACKGROUND,
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: COLORS.BACKGROUND,
    padding: 15,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 20,
  },
  retryButtonText: {
    color: COLORS.PRIMARY,
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_MEDIUM,
    fontWeight: 'bold',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  modalContent: {
    backgroundColor: COLORS.BACKGROUND,
    borderRadius: 8,
    width: '75%',
    maxWidth: 250,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  modalTitle: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_MEDIUM,
    fontWeight: 'bold',
    color: COLORS.PRIMARY,
    flex: 1,
  },
  closeButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.PRIMARY,
  },
  modalBody: {
    padding: 8,
    maxHeight: 250,
  },
  featureTitle: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL,
    fontWeight: 'bold',
    color: COLORS.PRIMARY,
    marginBottom: 3,
    marginTop: 6,
  },
  featureDescription: {
    fontSize: SMARTWATCH_CONSTANTS.FONT_SIZE_SMALL - 1,
    color: '#666',
    lineHeight: 16,
    marginBottom: 6,
  },
});

