rootProject.name = 'E-Responde-Smartwatch'
include ':app'
include ':react-native-community-geolocation'
project(':react-native-community-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/geolocation/android')
includeBuild('../node_modules/@react-native/gradle-plugin')

